title:              히지노 블로그
email:              wowboya@naver.com
description:        히지노 블로그
author:             Hyginus
baseurl:
url:                "https://wowboya.github.io"
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# Social Profiles
github_username:    wowboya

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
